package com.hotel.system.log;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.hotel.system.config.AppConfig;
import com.hotel.system.state.IterationResult;
import com.hotel.system.state.Turn;
import com.hotel.system.state.model.Alternative;
import com.hotel.system.state.model.ComponentSpec;
import com.hotel.system.state.model.CriticIssue;
import com.hotel.system.state.model.DriverCheck;
import com.hotel.system.state.model.GoalCheck;
import com.hotel.system.state.model.InterfaceSpec;
import com.hotel.system.util.TimeUtil;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.List;

/**
 * Emits two files:
 *   - conversation_log.md: every Turn with timestamps and per-turn token usage
 *   - architecture_report.md: report structured per the PDF assignment Appendix:
 *       一、Output results of ADD (Step 1 + Iterations 1..4 with Step 2-7 subsections)
 *       二、Interaction Cost Analysis (table + per-iteration breakdown)
 *       三、Individual Reflection (placeholder for the human team to fill)
 *     Plus a Multi-Agent System Overview header and per-iteration Critic appendix.
 */
public final class MarkdownLogWriter {
    private final Path outDir;
    private final ObjectMapper mapper;
    private final Path conversationPath;
    private final Path reportPath;

    public MarkdownLogWriter(Path outDir, ObjectMapper mapper) {
        this.outDir = outDir;
        this.mapper = mapper;
        this.conversationPath = outDir.resolve("conversation_log.md");
        this.reportPath = outDir.resolve("architecture_report.md");
    }

    public void initFiles() throws IOException {
        Files.writeString(conversationPath, "", StandardCharsets.UTF_8);
        Files.writeString(reportPath, "", StandardCharsets.UTF_8);
    }

    // -- Conversation log ----------------------------------------------------

    public void appendConversationHeader(String priorKnowledge) throws IOException {
        String s = """
                # Conversation Log

                ## Prior Knowledge

                ```text
                %s
                ```

                ## Turns

                """.formatted(priorKnowledge.trim());
        append(conversationPath, s);
    }

    public void appendConversationTurn(Turn t) throws IOException {
        String tokens = "prompt=%d, completion=%d, total=%d".formatted(
                t.getPromptTokens(), t.getCompletionTokens(), t.getTotalTokens());
        String s = """
                ### %s — %s

                **Input**

                ```text
                %s
                ```

                **Output**

                ```json
                %s
                ```

                **Tokens**
                %s

                """.formatted(t.getTs(), t.getNode(), t.getInput().trim(), t.getOutputJson().trim(), tokens);
        append(conversationPath, s);
    }

    public void appendConversationNote(String note) throws IOException {
        String s = """
                #### Note (%s)

                %s

                """.formatted(TimeUtil.nowIso(), note.trim());
        append(conversationPath, s);
    }

    // -- Architecture report -------------------------------------------------

    /**
     * Title + Multi-Agent System Overview (roles, dialogue rules, workflow).
     * Always called once before any iteration appendage.
     */
    public void appendArchitectureHeader(AppConfig cfg) throws IOException {
        String s = """
                # Architecture Design Report — Hotel Pricing System (HPS)

                _Generated by a Multi-Agent ADD 3.0 workflow._
                - Paradigm: %s
                - LLM: %s
                - Iterations planned: %d (max revisions per iteration: %d)

                ## 0. Multi-Agent System Overview

                ### 0.1 Roles
                | Role | Responsibility | System prompt source |
                |------|----------------|----------------------|
                | Orchestrator | Set the fixed iteration goal (matches the PDF iteration plan) and route to Architect. | `prompts/orchestrator_system.md` |
                | Architect | Produce one ADD iteration: Step 3 element to refine, Step 4 alternatives, Step 5 components with interfaces, Step 6 Mermaid views, Step 7 goal-check. | `prompts/architect_system.md` |
                | Critic | Verify required-driver coverage for THIS iteration; emit per-driver verdicts and severity-classified issues (BLOCK / WARN / NIT). | `prompts/critic_system.md` |
                | ContextCompactor | Compress prior iteration results into <= ~1.5 KB while preserving driver IDs and unresolved BLOCK/WARN items. | `prompts/context_compactor_system.md` |
                | HumanCheckpoint | Optional human gate before and after each iteration (`approve` / `retry`). Auto-approve supported via configuration. | `prompts/human_checkpoint_before.md`, `prompts/human_checkpoint_after.md` |

                ### 0.2 Dialogue Rules
                1. Architect runs first per iteration; Critic reviews its output against the required drivers for that iteration.
                2. If Critic returns any BLOCK issue, `pass=false` and Architect re-runs with the issues injected via `architect_critic_block.md`. At most `max_revisions` revision rounds per iteration.
                3. Unresolved BLOCK / WARN issues plus any `deferred` driver from Step 7 are written into `prior_carryover` and injected into the next iteration's Architect prompt.
                4. Each agent must only use `prior_knowledge` plus the compacted history; external domain knowledge, few-shot examples, and requirement reinterpretation are forbidden.
                5. Every `decision_log` entry must verbatim-quote at least one driver ID and snippet from `prior_knowledge`.

                ### 0.3 Workflow
                ```
                START -> Orchestrator -> HumanCheckpointBefore
                       -> Architect <-> Critic   (<= %d revisions; BLOCK forces revise)
                       -> Scribe -> ContextCompactor -> HumanCheckpointAfter
                       -> NextIteration (until 4 iterations completed) -> END
                ```
                Retry at HumanCheckpointAfter loops back to Architect (with current carryover).
                """.formatted(safe(cfg.paradigm), safe(cfg.openAiModel), cfg.iterations, cfg.maxRevisions, cfg.maxRevisions);
        append(reportPath, s);
    }

    /**
     * Section 一 prelude: ADD Step 1 (Review Inputs) including a dump of prior knowledge
     * and the fixed iteration → driver allocation table for Step 2.
     */
    public void appendReportSectionOne(String priorKnowledge, AppConfig cfg) throws IOException {
        String allocation = """
                ### Iteration → Required Drivers (fixed plan)
                | Iteration | Goal | Required drivers |
                |---|---|---|
                | 1 | Establishing an Overall System Structure | CRN-1, CON-1, CON-2, CON-6 |
                | 2 | Identifying Structures to Support Primary Functionality | HPS-1, HPS-2, HPS-3, HPS-4, HPS-5, HPS-6, CON-5 |
                | 3 | Addressing Reliability and Availability Quality Attributes | QA-2, QA-3, QA-8 |
                | 4 | Addressing Development and Operations | QA-5, QA-6, QA-7, QA-9, CON-3, CON-4 |
                """;
        String s = """

                ## 一、Output results of ADD

                ### ADD Step 1 — Review Inputs
                The complete set of architectural drivers (use cases, quality attributes, architectural concerns, constraints) provided to the multi-agent system as `prior_knowledge` is shown below. No external knowledge is permitted.

                <details><summary>Click to expand prior_knowledge.md verbatim</summary>

                ```text
                %s
                ```
                </details>

                %s
                """.formatted(priorKnowledge.trim(), allocation);
        append(reportPath, s);
    }

    /**
     * One full iteration block: ADD Step 2..7 subsections, Mermaid full + delta diagrams,
     * Critic per-driver verdict table, severity-bucketed issues, and decision log.
     * Also embeds the raw Architect / Critic JSON in collapsible appendices for traceability.
     */
    public void appendArchitectureIteration(IterationResult r) throws IOException {
        int it = r.getIteration();
        StringBuilder b = new StringBuilder(8192);

        b.append("\n### Iteration ").append(it).append(" — ").append(safe(r.getGoal())).append("\n\n");
        b.append("_Timestamp: ").append(safe(r.getTs()))
                .append(" · Revisions used: ").append(r.getRevisionsUsed())
                .append(" · Critic pass: ").append(r.isCriticPass())
                .append("_\n\n");

        // Step 2
        b.append("#### ADD Step 2 — Iteration Goal & Selected Drivers\n");
        b.append("- **Iteration goal:** ").append(safe(r.getGoal())).append("\n");
        if (!r.getIterationFocus().isBlank()) {
            b.append("- **Architect focus:** ").append(safe(r.getIterationFocus())).append("\n");
        }
        b.append("- **Required drivers for this iteration:** ");
        if (r.getRequiredDrivers().isEmpty()) {
            b.append("(none)\n\n");
        } else {
            b.append(String.join(", ", r.getRequiredDrivers())).append("\n\n");
        }

        // Step 3
        b.append("#### ADD Step 3 — Element(s) to Refine\n");
        b.append(r.getStep3Element().isBlank() ? "_(not provided)_\n\n" : (safe(r.getStep3Element()) + "\n\n"));

        // Step 4
        b.append("#### ADD Step 4 — Design Concepts Considered\n");
        b.append(renderAlternativesTable(r.getStep4Alternatives())).append("\n");

        // Step 5
        b.append("#### ADD Step 5 — Instantiated Elements, Responsibilities, and Interfaces\n");
        b.append(renderComponentsBlock(r.getStep5Components())).append("\n");

        // Step 6
        b.append("#### ADD Step 6 — Views (Mermaid)\n");
        b.append("**Full carry-over view**\n\n");
        b.append("```mermaid\n").append(nonEmpty(r.getStep6DiagramFullMermaid(), r.getMermaid(), "flowchart LR\n  empty[\"no diagram\"]"));
        b.append("\n```\n\n");
        if (!r.getStep6DiagramDeltaMermaid().isBlank()) {
            b.append("<details><summary><b>Delta view (only this iteration's additions)</b></summary>\n\n");
            b.append("```mermaid\n").append(r.getStep6DiagramDeltaMermaid()).append("\n```\n\n</details>\n\n");
        }

        // Step 7
        b.append("#### ADD Step 7 — Analysis & Goal Review\n");
        b.append(renderGoalCheckTable(r.getStep7GoalCheck())).append("\n");

        // Critic review block (still under Section 二 to keep iteration as a self-contained unit)
        b.append("#### Critic Review\n");
        b.append("**Driver check (per required driver):**\n\n");
        b.append(renderDriverCheckTable(r.getCriticDriverChecks())).append("\n");
        b.append("**Issues by severity:**\n\n");
        b.append(renderIssuesBuckets(r.getCriticIssuesTyped())).append("\n");

        // Decision log
        b.append("#### Decision Log\n");
        if (r.getDecisionLog().isEmpty()) {
            b.append("_(none recorded)_\n\n");
        } else {
            for (String d : r.getDecisionLog()) b.append("- ").append(d).append("\n");
            b.append("\n");
        }

        // Carryover to next iteration
        if (!r.getCarryoverForNextIteration().isBlank()) {
            b.append("#### Carry-over to next iteration\n");
            b.append("```text\n").append(r.getCarryoverForNextIteration()).append("\n```\n\n");
        }

        // Per-iteration interaction cost (already aggregated in scribe stats)
        ObjectNode cost = mapper.createObjectNode();
        cost.put("prompt_tokens", r.getPromptTokens());
        cost.put("completion_tokens", r.getCompletionTokens());
        cost.put("total_tokens", r.getTotalTokens());
        cost.put("human_turns", r.getHumanTurns());
        cost.put("agent_turns", r.getAgentTurns());
        cost.put("duration_ms", r.getDurationMs());
        b.append("#### Interaction Cost (this iteration)\n");
        b.append("```json\n");
        try {
            b.append(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(cost));
        } catch (Exception e) {
            b.append(cost.toString());
        }
        b.append("\n```\n\n");

        // Raw JSON appendices for traceability
        if (!r.getArchitectRawJson().isBlank()) {
            b.append("<details><summary><b>Appendix A — Architect raw JSON</b></summary>\n\n");
            b.append("```json\n").append(r.getArchitectRawJson()).append("\n```\n\n</details>\n\n");
        }
        if (!r.getCriticRawJson().isBlank()) {
            b.append("<details><summary><b>Appendix B — Critic raw JSON</b></summary>\n\n");
            b.append("```json\n").append(r.getCriticRawJson()).append("\n```\n\n</details>\n\n");
        }

        append(reportPath, b.toString());
    }

    /** Section 二: cumulative interaction-cost table across all iterations. */
    public void appendInteractionCostTable(AppConfig cfg, List<IterationResult> all) throws IOException {
        long totPrompt = 0, totCompletion = 0, totTotal = 0, totHuman = 0, totAgent = 0;
        long totDuration = 0;
        for (IterationResult r : all) {
            totPrompt += r.getPromptTokens();
            totCompletion += r.getCompletionTokens();
            totTotal += r.getTotalTokens();
            totHuman += r.getHumanTurns();
            totAgent += r.getAgentTurns();
            totDuration += r.getDurationMs();
        }
        String tokensK = String.format("%.2f", totTotal / 1000.0);
        String minutes = String.format("%.2f", totDuration / 60000.0);

        StringBuilder b = new StringBuilder(2048);
        b.append("\n## 二、Interaction Cost Analysis\n\n");
        b.append("| The way of completing the assignment | The LLM used | Number of Human Interactions (turns) | Token Consumption (K tokens) | Time Cost (min) |\n");
        b.append("|---|---|---|---|---|\n");
        b.append("| ").append(safe(cfg.paradigm))
         .append(" | ").append(safe(cfg.openAiModel))
         .append(" | ").append(totHuman)
         .append(" | ").append(tokensK)
         .append(" | ").append(minutes)
         .append(" |\n\n");

        b.append("### Per-iteration breakdown\n\n");
        b.append("| Iter | Goal | Revisions | Human turns | Agent turns | Prompt tokens | Completion tokens | Total tokens | Duration (s) |\n");
        b.append("|---|---|---|---|---|---|---|---|---|\n");
        for (IterationResult r : all) {
            b.append("| ").append(r.getIteration())
             .append(" | ").append(safe(r.getGoal()))
             .append(" | ").append(r.getRevisionsUsed())
             .append(" | ").append(r.getHumanTurns())
             .append(" | ").append(r.getAgentTurns())
             .append(" | ").append(r.getPromptTokens())
             .append(" | ").append(r.getCompletionTokens())
             .append(" | ").append(r.getTotalTokens())
             .append(" | ").append(String.format("%.1f", r.getDurationMs() / 1000.0))
             .append(" |\n");
        }
        b.append("| **Total** | — | — | **").append(totHuman).append("** | **").append(totAgent)
         .append("** | **").append(totPrompt).append("** | **").append(totCompletion)
         .append("** | **").append(totTotal).append("** | **")
         .append(String.format("%.1f", totDuration / 1000.0)).append("** |\n\n");
        append(reportPath, b.toString());
    }

    /** Section 三 placeholder. The team must fill this section by hand. */
    public void appendReflectionPlaceholder() throws IOException {
        String s = """

                ## 三、Individual Reflection

                ### 1) Problems encountered and the solutions adopted
                _TODO (write by hand, 300–800 words):_
                - What went well / poorly during the multi-agent ADD workflow?
                - Where did the agents add the most value? Where did they produce shallow output?
                - How did Critic's BLOCK loop and carryover affect the design quality?
                - What prompt or workflow change would you make if running this again?

                ### 2) A detailed account of personal contributions

                | Name (Chinese) | Contributions |
                |---|---|
                | _TODO_ | _e.g., Prompt design and ADD-rule encoding_ |
                | _TODO_ | _e.g., Engine / Writer Java implementation_ |
                | _TODO_ | _e.g., Run orchestration, reflection writing, report integration_ |
                """;
        append(reportPath, s);
    }

    // -- Renderers -----------------------------------------------------------

    private static String renderAlternativesTable(List<Alternative> alts) {
        if (alts == null || alts.isEmpty()) {
            return "_No alternatives recorded by Architect._\n";
        }
        StringBuilder b = new StringBuilder();
        b.append("| # | Concept | Pros | Cons | Chosen | Rationale |\n");
        b.append("|---|---|---|---|---|---|\n");
        int i = 1;
        for (Alternative a : alts) {
            b.append("| ").append(i++)
             .append(" | ").append(esc(a.concept()))
             .append(" | ").append(esc(a.pros()))
             .append(" | ").append(esc(a.cons()))
             .append(" | ").append(a.chosen() ? "✅" : "")
             .append(" | ").append(esc(a.rationale()))
             .append(" |\n");
        }
        return b.toString();
    }

    private static String renderComponentsBlock(List<ComponentSpec> cs) {
        if (cs == null || cs.isEmpty()) {
            return "_No components recorded by Architect._\n";
        }
        StringBuilder b = new StringBuilder();
        for (ComponentSpec c : cs) {
            b.append("- **").append(esc(c.name())).append("**\n");
            if (!c.responsibilities().isEmpty()) {
                b.append("  - Responsibilities:\n");
                for (String r : c.responsibilities()) b.append("    - ").append(r).append("\n");
            }
            if (!c.providedInterfaces().isEmpty()) {
                b.append("  - Provided interfaces:\n\n");
                b.append("    | Name | Signature / Topic | Protocol | Payload schema |\n");
                b.append("    |---|---|---|---|\n");
                for (InterfaceSpec i : c.providedInterfaces()) {
                    b.append("    | ").append(esc(i.name()))
                     .append(" | ").append(esc(i.signatureOrTopic()))
                     .append(" | ").append(esc(i.protocol()))
                     .append(" | ").append(esc(i.payloadSchema()))
                     .append(" |\n");
                }
                b.append("\n");
            }
            if (!c.requiredInterfaces().isEmpty()) {
                b.append("  - Required interfaces: ").append(String.join(", ", c.requiredInterfaces())).append("\n");
            }
            b.append("\n");
        }
        return b.toString();
    }

    private static String renderGoalCheckTable(List<GoalCheck> gs) {
        if (gs == null || gs.isEmpty()) {
            return "_No Step 7 goal-check entries recorded._\n";
        }
        StringBuilder b = new StringBuilder();
        b.append("| Driver | Mechanism in design | Quantitative evidence | Verdict | Carry-over note |\n");
        b.append("|---|---|---|---|---|\n");
        for (GoalCheck g : gs) {
            b.append("| ").append(esc(g.driverId()))
             .append(" | ").append(esc(g.mechanismInDesign()))
             .append(" | ").append(esc(g.quantitativeEvidence()))
             .append(" | ").append(esc(g.verdict()))
             .append(" | ").append(esc(g.carryoverNote()))
             .append(" |\n");
        }
        return b.toString();
    }

    private static String renderDriverCheckTable(List<DriverCheck> ds) {
        if (ds == null || ds.isEmpty()) {
            return "_No driver-check entries from Critic._\n";
        }
        StringBuilder b = new StringBuilder();
        b.append("| Driver | Evidence in design | Evidence in diagram | Verdict |\n");
        b.append("|---|---|---|---|\n");
        for (DriverCheck d : ds) {
            b.append("| ").append(esc(d.driverId()))
             .append(" | ").append(esc(d.evidenceInDesign()))
             .append(" | ").append(esc(d.evidenceInDiagram()))
             .append(" | ").append(esc(d.verdict()))
             .append(" |\n");
        }
        return b.toString();
    }

    private static String renderIssuesBuckets(List<CriticIssue> is) {
        if (is == null || is.isEmpty()) {
            return "_No Critic issues._\n";
        }
        StringBuilder b = new StringBuilder();
        for (CriticIssue.Severity sev : CriticIssue.Severity.values()) {
            List<CriticIssue> bucket = is.stream().filter(i -> i.severity() == sev).toList();
            b.append("**").append(sev.name()).append("** (").append(bucket.size()).append(")\n");
            if (bucket.isEmpty()) {
                b.append("- _(none)_\n\n");
                continue;
            }
            for (CriticIssue ci : bucket) {
                b.append("- `").append(esc(ci.driverIdOrConcernId())).append("` — ");
                b.append(esc(ci.description()));
                if (ci.suggestedFix() != null && !ci.suggestedFix().isBlank()) {
                    b.append("  \n  · _Suggested fix:_ ").append(esc(ci.suggestedFix()));
                }
                b.append("\n");
            }
            b.append("\n");
        }
        return b.toString();
    }

    // -- helpers -------------------------------------------------------------

    private static String esc(String s) {
        if (s == null) return "";
        // Escape pipes so cells stay in one column.
        return s.replace("|", "\\|").replace("\n", " ");
    }

    private static String safe(String s) {
        return s == null ? "" : s;
    }

    private static String nonEmpty(String... candidates) {
        for (String s : candidates) {
            if (s != null && !s.isBlank()) return s;
        }
        return "";
    }

    private void append(Path p, String s) throws IOException {
        Files.writeString(p, s, StandardCharsets.UTF_8,
                Files.exists(p) ? StandardOpenOption.APPEND : StandardOpenOption.CREATE);
    }
}
