package com.hotel.system.log;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.hotel.system.state.IterationResult;
import com.hotel.system.state.Turn;
import com.hotel.system.util.TimeUtil;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public final class MarkdownLogWriter {
    private final Path outDir;
    private final ObjectMapper mapper;
    private final Path conversationPath;
    private final Path reportPath;

    public MarkdownLogWriter(Path outDir, ObjectMapper mapper) {
        this.outDir = outDir;
        this.mapper = mapper;
        this.conversationPath = outDir.resolve("conversation_log.md");
        this.reportPath = outDir.resolve("architecture_report.md");
    }

    public void initFiles() throws IOException {
        Files.writeString(conversationPath, "", StandardCharsets.UTF_8);
        Files.writeString(reportPath, "", StandardCharsets.UTF_8);
    }

    public void appendConversationHeader(String priorKnowledge) throws IOException {
        String s = """
                # Conversation Log

                ## Prior Knowledge

                ```text
                %s
                ```

                ## Turns

                """.formatted(priorKnowledge.trim());
        append(conversationPath, s);
    }

    public void appendArchitectureHeader() throws IOException {
        String s = """
                # Architecture Report

                This report is generated by a 4-iteration multi-agent workflow (ADD-style).

                """;
        append(reportPath, s);
    }

    public void appendConversationTurn(Turn t) throws IOException {
        String tokens = """
                prompt=%d, completion=%d, total=%d
                """.formatted(t.getPromptTokens(), t.getCompletionTokens(), t.getTotalTokens()).trim();
        String s = """
                ### %s — %s

                **Input**

                ```text
                %s
                ```

                **Output**

                ```json
                %s
                ```

                **Tokens**
                %s

                """.formatted(t.getTs(), t.getNode(), t.getInput().trim(), t.getOutputJson().trim(), tokens);
        append(conversationPath, s);
    }

    public void appendConversationNote(String note) throws IOException {
        String s = """
                #### Note (%s)

                %s

                """.formatted(TimeUtil.nowIso(), note.trim());
        append(conversationPath, s);
    }

    public void appendArchitectureIteration(IterationResult r) throws IOException {
        ObjectNode meta = mapper.createObjectNode();
        meta.put("iteration", r.getIteration());
        meta.put("ts", r.getTs());
        meta.put("revisions_used", r.getRevisionsUsed());
        meta.put("issues_count", r.getIssues().size());

        String issues = r.getIssues().isEmpty()
                ? "- None"
                : r.getIssues().stream().map(x -> "- " + x).reduce((a, b) -> a + "\n" + b).orElse("- None");

        String decisions = r.getDecisionLog().isEmpty()
                ? "- None"
                : r.getDecisionLog().stream().map(x -> "- " + x).reduce((a, b) -> a + "\n" + b).orElse("- None");

        ObjectNode cost = mapper.createObjectNode();
        cost.put("prompt_tokens", r.getPromptTokens());
        cost.put("completion_tokens", r.getCompletionTokens());
        cost.put("total_tokens", r.getTotalTokens());
        cost.put("human_turns", r.getHumanTurns());
        cost.put("agent_turns", r.getAgentTurns());
        cost.put("duration_ms", r.getDurationMs());

        String s = """
                ## Iteration %d

                **Goal**
                %s

                **Metadata**
                ```json
                %s
                ```

                **Design**
                %s

                **Diagram (Mermaid)**
                ```mermaid
                %s
                ```

                **Critic Issues**
                %s

                **Decision Log**
                %s

                **Interaction Cost**
                ```json
                %s
                ```

                """.formatted(
                r.getIteration(),
                r.getGoal().trim(),
                mapper.writerWithDefaultPrettyPrinter().writeValueAsString(meta).trim(),
                r.getDesign().trim(),
                r.getMermaid().trim(),
                issues,
                decisions,
                mapper.writerWithDefaultPrettyPrinter().writeValueAsString(cost).trim()
        );

        append(reportPath, s);
    }

    private void append(Path p, String s) throws IOException {
        Files.writeString(p, s, StandardCharsets.UTF_8, Files.exists(p) ? java.nio.file.StandardOpenOption.APPEND : java.nio.file.StandardOpenOption.CREATE);
    }
}
